# Generated by Django 5.1.6 on 2025-03-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='Category e.g. Office, Living Room', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('default_pieces', models.TextField(blank=True, help_text="Pieces e.g. '50x30:2, 40x10:3'")),
            ],
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tool_type', models.CharField(choices=[('blade', 'Blade'), ('laser', 'Laser')], max_length=10)),
                ('thickness', models.FloatField(blank=True, help_text='Blade thickness or Laser beam diameter (mm)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Cutting speed in mm/s', null=True)),
                ('power', models.FloatField(blank=True, help_text='Laser power if tool_type=laser (Watts)', null=True)),
                ('focus', models.FloatField(blank=True, help_text='Laser focus if tool_type=laser (mm offset)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any extra details', null=True)),
                ('description', models.TextField(blank=True, help_text='A more detailed description or usage guidelines', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('stock_width', models.FloatField()),
                ('stock_height', models.FloatField()),
                ('status', models.CharField(default='processing', max_length=20)),
                ('utilization', models.FloatField(default=0.0)),
                ('layout_data', models.TextField(blank=True, null=True)),
                ('assembly_steps', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furniture_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.furnituretemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tool_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.toolconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='optimizer.project')),
            ],
        ),
    ]
