# Generated by Django 5.1.6 on 2025-04-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='algorithm',
            field=models.CharField(default='lp', help_text='Optimization method: lp, ga, or hybrid', max_length=20),
        ),
    ]
