# Generated by Django 5.1.6 on 2025-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_project_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stock_depth',
            field=models.FloatField(default=5.0, help_text='Depth (thickness) of the base stock in mm'),
        ),
    ]
