# Generated by Django 5.1.6 on 2025-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_project_algorithm_project_tool_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layout_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='algorithm',
            field=models.CharField(default='LP', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tool_type',
            field=models.CharField(default='blade', max_length=50),
            preserve_default=False,
        ),
    ]
