# Generated by Django 5.1.6 on 2025-03-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_project_layout_data_alter_project_algorithm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_pieces', models.TextField(help_text='JSON list of pieces. E.g.: [{"label": "Leg", "width": 50, "height": 50, "quantity": 4}, {"label": "Top", "width": 100, "height": 60, "quantity": 1}]')),
            ],
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tool_type', models.CharField(choices=[('blade', 'Blade'), ('laser', 'Laser')], max_length=10)),
                ('size', models.FloatField(help_text='Blade thickness or Laser beam diameter')),
                ('speed', models.FloatField(help_text='Cutting speed in mm/s')),
                ('power', models.FloatField(blank=True, help_text='Laser power if tool_type=laser', null=True)),
                ('focus', models.FloatField(blank=True, help_text='Laser focus if tool_type=laser', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='piece',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='furniture_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.furnituretemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='tool_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.toolconfig'),
        ),
    ]
